from GraphModel.Graph import Graph
from GraphModel.Node import Node


class GraphContentLinus:

    def __init__(self, graph: Graph):
        self.create_linus_nodes(graph)

    @staticmethod
    def create_linus_nodes(graph):
        """
        Inhalt der einzelnen Knoten
        """

        header_linus_node = Node("Linus Torvald ist das Gesicht hinter Linux. Er ist dafür verantwortlich das "
                                 "es heute Linux gibt. "
                                 "Esprofitieren viele Programmierer von seiner Arbeit. Das beste Beispiel dafür ist "
                                 "git, welches Linus auch selber entwickelt hatte. Dies ist eine Versionsverwaltung "
                                 "die es Programmierern zusammen an "
                                 "verschiedenen Stellen im Code gleichzeitig zu arbeiten.\n"
                                 "Dieser Knotenteil des Wissensgraph „Die bekanntesten Informatiker:innen und Ihre "
                                 "Beiträge zum "
                                 "Fachgebiet“ behandelt alle wichtigen Informationen zu Linus Torvald. Dies beinhaltet "
                                 "seine Kindheit und sein Bildungsweg. Des weiteren sind Informationen zu Git und "
                                 "Linux und anderen "
                                 "Projekten zu finden, mit denen sich Linus auseinander gesetzt hat. Unter "
                                 "anderen werden auch die Hürden genannt, die es bei der Entwicklung von Linux gab. "
                                 "Es gibt Informationen zum Namenstreit vom „Linux“ und welche Rolle Linux in der "
                                 "Industrie und der allgemeinen Technologie spielt. ", "Linus Torvald",
                                 "Linus_picture.jpg")

        topic_node = Node("Linus Torvalds wurde am 28.12.1969 in Helsinki geboren. Sein voller Name lautet "
                          "Linus Benedict "
                          "Torvalds. Seine Eltern heißen Anna Torvalds uns Nils Torvalds. "
                          " Beide waren damals Studenten an "
                          "der Universität Helsinki und haben an der Studentenbewegung der 1960er "
                          "Jahre teilgenommen. \n"
                          "Im weiteren Verlauf wurde die Mutter Torvalds Übersetzerin bei der "
                          "finnischen Nachrichtenagentur "
                          "STT. Der Vater, Nils Torvalds wurde nach der Karriere als Fernseh- und Rundfunkjournalist "
                          "Mitglied des Europaparlaments.Die Familie Torvalds gehört dabei zur schwedischsprachigen "
                          "Minderheit der Finnen.\n\n"
                          "Linus Torvalds hat eine Schwester, die 16 Monate nach ihm geboren wurde und trägt den Namen "
                          "Sara. Die Eltern von Linus trennten sich als Linus 7 Jahre alt war. Linus "
                          "bekam noch einen Bruder "
                          "väterlicherseits. Dieser heißt Leo Torvalds und wurde zwei Jahre nach der "
                          "Trennung von Nils und "
                          "Anna Torvalds geboren. \n\n"
                          "Linus wurde nach dem berühmten Chemiker Linus Carl Pauling benannt. Der Nachname wurde "
                          "durch den Namen des Großvater Väterlicherseits geschaffen. Dieser hieß Ole "
                          "Torvald Elis Saxberg "
                          "Karanko. \n\n"
                          "Während der Schulzeit wuchs Linus im Helsinkier Stadtteil Punavouri. Laut dem "
                          "Worten von Linus "
                          "selbst, bezeichnet er sich als „Freek“, „Nerd“ und „Geek“. \n\n"
                          "Linus hatte pflegte wenig Interesse an Sport. Er widmete sich eher den Modellbau,"
                          "und widmete seine Zeit den Büchern der Genres Horror und Science-Fiction. \n\n"
                          "(Quelle2)",
                          "Kindheit und Jugend von Linus Torvald")

        topic1_node = Node("Die Schulische Laufbahn begann Linus in der schwedisch-sprachigen Cygnaeus-Grundschule."
                           "Später wechselte er dann auf das schwedische Allgemeingymnasium in Kruununhaka. Da Linus "
                           "sein Geburtstag am Jahresende hat, war er folglich immer der jüngste in der jeweiligen "
                           "Schulklasse,"
                           "die er im laufe seiner Schulzeit besuchte. \n\n"
                           "Der erste Kontakt mit Computern erfolgte bei Linus als er 11 Jahre alt war. "
                           "Dieser Computer war "
                           "ein Commodore VC 20, welcher er von seinem Großvater bekam. Linus lernte damit die BASIC-"
                           "Programmierung und las Handbücher von Computern. Seine ersten Programmiererfahrungen "
                           "erhielt"
                           "Linus auf einem Sinqlair QL. Er disassembilierte das Betriebssystem QDOS und schrieb einen "
                           "eigenen Floppy-Controller-Treiber. Die Disassembilisierung des QDOS half Linus dabei die "
                           "Architektur besser zu verstehen. \n\n"
                           "Leisten konnte sich Linus den Rechner nur, da er Ferienjobs annahm, Stipendien erhielt und "
                           "Kredite von seinem Vater nahm. \n"
                           "(Quelle2) \n\n",
                           "Bildungsweg und erste Interessen in den Themenbereich der Informatik ")

        topic2_node = Node("Linus Torvalds begann 1986 mit der Programmierung eigener Treiber für seinen "
                           "Sinclair-Computer."
                           "1991, als 386-Intel PCs populär wurden, kaufte er sich ein solches Gerät und setzte sich "
                           "intensiv mit "
                           "der Programmierung von 386 CPUs auseinander. Er nutzte das Unix-verwandte MINIX als "
                           "Betriebssystem, das er bereits 1990 an seiner Universität kennengelernt hatte. Aufgrund "
                           "seiner "
                           "Unzufriedenheit mit dem Terminal-Emulatorprogramm in MINIX begann er, einen eigenen "
                           "Terminal Emulator zu entwickeln, der schließlich zu einem eigenständigen "
                           "Betriebssystem führte. \n\n"
                           "Am 17. September 1991 wurde die erste Version seines Betriebssystems, damals noch als "
                           ",,Freak´´ "
                           "bezeichnet, fertiggestellt. Nach etwa 6 Monaten wurde es in ,,Linux´´ umbenannt. "
                           " Linus Torvalds "
                           "stellte sein Projekt öffentlich vor und bat um Vorschläge für weitere Funktionen. "
                           "er Sourcecode "
                           "wurde frei zugänglich gemacht, und die Entwicklung erhielt Unterstützung aus der Internet- "
                           "Community. \n\n"
                           "Die Bezeichnung ,,GNU/Linux´´ entstand, da Linux stark von der GNU-Software "
                           "profitierte. Der "
                           "Name ,,Linux´´ wurde durch einen rechtlichen Zwischenfall auf Linus Torvalds "
                           "übertragen, um die "
                           "Weiterentwicklung zu gewährleisten. Das Maskottchen ,,Tux der Pinguin´´ wurde "
                           "gewählt, weil "
                           "Torvalds von einem Pinguin gebissen wurde. \n\n"
                           "(Quelle3)", "Motivationen und allgemeine Motive zur Entwicklung von Linux")

        topic3_node = Node("Part 1: Vorteile freier Entwicklung und Verteilung: \n\n"
                           "Part 2: Berufliche Entwicklung von Linus Torvalds: \n\n"
                           "Part 3: Linux Foundation und Distributoren: \n\n",
                           "Linux und die Beiträge von Linus dazu")

        topic3v1_node = Node("Die freie Entwicklung von Linux ermöglicht eine Benutzerorientierung, "
                             "da nur die am meisten"
                             "benötigten Features integriert werden. Die dynamische Entwicklung führt dazu, "
                             "dass nur die "
                             "wichtigsten Ideen akzeptiert und in den offiziellen Systemkern aufgenommen werden. "
                             "Linux hält "
                             "die Spezifikationen für System V und BSD Unix Programme ein. \n\n"
                             "Die Offenheit ermöglicht es, neue Eigenschaften durch verschiedene Betriebssystemfirmen "
                             "hinzuzufügen, wie die Dateisystemunterstützung durch SGI mit XFS. Linux und verwandte "
                             "Betriebssysteme entstanden durch die Arbeit der Internet-Community "
                             " und werden zunehmend von "
                             "IT-Firmen unterstützt.\n\n "
                             "Linus Torvalds hatte klare Ziele bei der Entwicklung von Linux. "
                             "Er wollte ein verbessertes "
                             "Betriebssystem im Vergleich zu MINIX schaffen, "
                             "ein Unix-ähnliches System für PCs entwickeln "
                             "und von Anfang an auf Open Source setzen. Die Zusammenarbeit mit einer globalen "
                             "Entwicklergemeinschaft war ein zentrales Anliegen, "
                             "um Ideen und Innovationen zu fördern. Die "
                             "Entwicklung von Linux sollte sich stets an den "
                             "tatsächlichen Bedürfnissen der Benutzer orientieren. \n\n"
                             "(Quelle 3)",
                             "Vorteile freier Entwicklung und Verteilung:")

        topic3v2_node = Node("Linus Torvalds arbeitete von März 1997 bis Juni 2003 für den Chiphersteller "
                             "Transmeta. Danach "
                             "wechselte er zum OSDL (Open Source Development Lab) und zog nach Portland, Oregon. Das "
                             "OSDL und die Free Standards Group schlossen sich im Januar 2007 zur Linux Foundation "
                             "zusammen. Linus Torvalds ist weiterhin aktiver Betreuer und Hauptentwickler "
                             "des Linux-Kernels "
                             "seit 1991. \n\n"
                             "(Quelle 3)",
                             "Berufliche Entwicklung von Linus Torvalds:")

        topic3v3_node = Node("Das OSDL und die Free Standards Group bildeten 2007 die "
                             "Linux Foundation. Distributoren sind "
                             "Entwicklerteams, die Installations fertige Softwarepakete basierend "
                             "auf dem Linux-Systemkern "
                             "anbieten. Diese Distributionen werden per Internet in Form von ISO "
                             "Images oder auf CD/DVD- "
                             "ROM kostengünstig zur Verfügung gestellt. Das eingenommene Geld wird "
                             "für die Entwickler und "
                             "den Support benötigt. Es existieren verschiedene Installationsweisen, "
                             "einschließlich Booten von "
                             "CD-ROM, DVD, Diskette, Netzwerk oder FTP-Server. Es gibt spezialisierte "
                             "Distributionen für "
                             "verschiedene Einsatzgebiete wie Data-Recovery oder Software-Router. \n\n"
                             "(Quelle 3)",
                             "Linux Foundation und Distributoren:")

        topic4_node = Node("Linus Torvalds sieht den Erfolg von Open-Source-Software "
                           "in einem pragmatischen Ansatz, der auf "
                           "Eigennutz und Vertrauen basiert. Für ihn steht im Vordergrund, "
                           "dass Open Source die Möglichkeit "
                           "bietet, individuellen Nutzen zu verfolgen, und nicht unbedingt, "
                           "die Gesellschaft zu verbessern. \n\n"
                           "Seiner Ansicht nach bedeutet Egoismus in diesem Kontext "
                           "nicht nur finanzielles Interesse, sondern "
                           "auch die Freiheit, an Systemen und Hardware zu arbeiten "
                           "und beispielsweise neue Funktionen zu "
                           "implementieren. Torvalds argumentiert, dass Unternehmen "
                           "ein starkes Eigeninteresse daran haben "
                           "sollten, zu Open-Source-Projekten wie Linux beizutragen. \n"
                           "Dies liegt daran, dass ihre Beiträge nicht nur ihre eigenen "
                           "Projekte in eine bestimmte Richtung "
                           "lenken können, sondern ihnen auch Wissensvorteile gegenüber Wettbewerbern verschaffen. Er "
                           "betont, dass es nicht akzeptabel ist, sich auf der Arbeit anderer auszuruhen. "
                           "Vertrauen spielt laut "
                           "Torvalds eine entscheidende Rolle in der Open-Source-Entwicklung. \n"
                           "Als Chefentwickler des Linux-Kernels, der von Tausenden von "
                           "Programmierern bearbeitet wird, ist "
                           "es wichtig, Vertrauen in die Zusammenarbeit zu haben. Das schließt ein, "
                           "sicherzustellen, dass "
                           "niemand versucht, das System zu manipulieren, selbst wenn die Diskussionen "
                           "kontrovers sind. "
                           "Gleichzeitig müssen alle Beteiligten darauf vertrauen können, dass er niemanden bevorzugt, "
                           "insbesondere keine Unternehmen. \n"
                           "Torvalds hebt hervor, dass seine Anstellung bei der Linux Foundation es ihm ermöglicht, "
                           "hauptberuflich an Linux zu arbeiten, und sein Vertrag stellt sicher, "
                           "dass sein Arbeitgeber keine"
                           "Vorgaben bei der Entwicklung machen kann. Zum Schluss betont Torvalds, "
                           "dass die vorinstallierte "
                           "Verfügbarkeit von Linux entscheidend für die Verbreitung auf Desktops ist. \n\n"
                           "Er zeigt sich hoffnungsvoll, dass Initiativen wie die Chromebox und Chromebooks von Google "
                           "sowie Projekte wie das Raspberry Pi dazu beitragen können, Linux einem breiteren Publikum "
                           "zugänglich zu machen, insbesondere auch jungen Menschen, die sonst "
                           "möglicherweise nicht mit "
                           "Computern oder Programmierung in Berührung kommen würden. \n\n"
                           "(Quelle 4)", "Einstellung von Linus zur Open Source Politik")

        topic5_node = Node("-->Linus Torvalds und die Diskussionen um GNU/Linux \n\n"
                           "-->Verhältnis zu Richard Stallman und dem GNU-Projekt \n\n"
                           "-->Lizenzierung von Linux und die GNU General Public License (GPL) \n\n",
                           "GNU und Linux Debatten")

        topic5v1_node = Node("Linus Torvalds und Richard Stallman führten Gespräche über die Benennung "
                             "des Betriebssystems. "
                             "Stallman unterstrich die Rolle des GNU-Projekts in der Systementwicklung und "
                             "plädierte dafür, es "
                             "als ,,GNU/Linux´´ zu bezeichnen. Torvalds bevorzugte den Ausdruck ,,Linux´´ "
                             "und wies darauf hin, "
                             "dass sein Beitrag, insbesondere der Linux-Kernel, entscheidend war. \n\n"
                             "Stallman betonte, dass die Bezeichnung die Prinzipien der Freiheit "
                             "repräsentiert. Torvalds "
                             "Perspektive wurde von manchen als technisch orientiert betrachtet, "
                             "ohne ausreichende Beachtung "
                             "der ideologischen Bedeutung von freier Software. \n\n"
                             "(Quelle5)",
                             "Linus Torvalds und die Diskussionen um GNU/Linux")

        topic5v2_node = Node("Die Auseinandersetzung über die Betriebssystembezeichnung "
                             "spiegelt die Spannungen zwischen "
                             "Linus Torvalds und Richard Stallman wider. Stallman, "
                             "der das GNU-Projekt leitet, betonte die "
                             "Wichtigkeit, das gesamte System als ,,GNU/Linux´´ zu "
                             "bezeichnen, um die Leistungen des GNU- "
                             "Projekts angemessen zu würdigen. Torvalds bevorzugte den Fokus auf den Linux-Kernel. \n\n"
                             "Stallman unternahm Versuche, die Einführung von "
                             "GNU/Linux durchzusetzen, einschließlich der "
                             "Ablehnung von Reden, wenn das GNU-Projekt nicht "
                             " angemessen anerkannt wurde. Dies führte zu "
                             "Spannungen zwischen den beiden Persönlichkeiten. \n\n"
                             "(Quelle 5)",
                             "Verhältnis zu Richard Stallman und dem GNU-Projekt")

        topic5v3_node = Node("Die Diskussion über die Betriebssystembezeichnung wirft auch "
                             "Fragen zur Lizenzierung auf. "
                             "Stallman und das GNU-Projekt bevorzugten die Verwendung der GNU GPL, um sicherzustellen, "
                             "dass das System und seine Software Freie Software bleiben. Stallman "
                             "betonte die Bedeutung der "
                             "Softwarefreiheit und sprach sich gegen die Nutzung unfreier Software, "
                             "wie Bitkeeper, für die "
                             "Entwicklung des Linux-Kernels aus. \n\n"
                             "Die Nutzung von Bitkeeper führte in der Freie-Software-Gemeinschaft "
                             " zu Bedenken, da es sich um "
                             "ein unfreies Versionskontrollsystem handelte. Stallman schlug vor, "
                             "alternative Lösungen mit freier "
                             "Software zu verwenden, um die Prinzipien der Freiheit zu wahren und "
                             "die Verwendung unfreier "
                             "Software zu vermeiden. \n\n"
                             "Insgesamt spiegelt die Auseinandersetzung zwischen Torvalds und "
                             "Stallman die verschiedenen "
                             "Philosophien bezüglich Freier Software wider, wobei Stallman die "
                             " ideologische Bedeutung betonte, "
                             "während Torvalds sich auf technische Aspekte konzentrierte. \n\n"
                             "(Quelle 5)",
                             "Lizenzierung von Linux und die GNU General Public License (GPL)")

        topic6_node = Node("In der Industrie gewinnt Linux auf Enterprise-Desktops zunehmend an Akzeptanz. Unternehmen "
                           "setzen verstärkt auf Linux-Betriebssysteme, insbesondere auf Servern im Kontext "
                           "von Cloud- und "
                           "Container-Anwendungen. Die Attraktivität von Linux resultiert aus seiner Flexibilität,"
                           "Container-Anwendungen. Die Attraktivität von Linux resultiert aus seiner Flexibilität, "
                           "Benutzerfreundlichkeit und vor allem den niedrigeren Kosten im Vergleich zu Windows oder "
                           "MacOS. Zusätzlich schätzen Unternehmen die Möglichkeiten der Personalisierung aufgrund der "
                           "Open-Source-Natur von Linux.\n\n"
                           "Verschiedene Linux-Distributionen sind auf dem Markt weit verbreitet. "
                           "Ubuntu, basierend auf "
                           "Debian, bietet eine moderne Desktop-Umgebung und ist kostenlos verfügbar. "
                           "Red Hat Enterprise"
                           "Linux (RHEL) ist für Desktops, Server und Cloud-Anwendungen beliebt, mit Standard- und "
                           "Premium-Supportoptionen. SUSE Linux Enterprise Desktop konzentriert sich auf "
                           "Benutzerfreundlichkeit und Sicherheitsfunktionen. Fedora, ein Community-basiertes Projekt, "
                           "eignet "
                           "sich für Desktops und bietet eine gute Community-Unterstützung. Linux Mint, basierend auf "
                           "Debian und Ubuntu, richtet sich an den gewöhnlichen Desktop-Endanwender "
                           " und bietet eine stabile "
                           "und benutzerfreundliche Umgebung. \n\n"
                           "Die Integration von Linux und Windows in industriellen Anwendungen ermöglicht es, "
                           "Echtzeit- "
                           "Anwendungen parallel auf einem PC laufen zu lassen. LxWin von "
                           "acontis technologies fügt ein 32-"
                           "oder 64-Bit-Realtime-fähiges Linux-Betriebssystem zu Windows hinzu, wodurch Anwendungen "
                           "beider Betriebssysteme gleichzeitig ausgeführt werden können. "
                           "Dies bietet Vorteile in Bezug auf "
                           "Hardware-Konsolidierung und ermöglicht die reibungslose "
                           " Fortsetzung von Steuerungsprozessen, "
                           "auch wenn Windows abstürzt. \n\n"
                           "Im Bereich von Embedded-Systemen verwenden viele Board-Hersteller Linux. Allerdings zeigt "
                           "sich, dass die Aktualisierung von Board Support Packages (BSP) oft kurzlebig ist, was "
                           "Sicherheitsbedenken aufwirft. ELinOS, basierend auf Yocto, "
                           "bietet eine Lightweight-Linux-Variante "
                           "mit geringem Speicherbedarf. Durch den Feature Configurator ermöglicht es "
                           "eine schnelle und "
                           "umfassende Konfiguration entsprechend betrieblicher Anforderungen. Mit Funktionen wie "
                           "SELinux-Erweiterung, CAPP-Compliance und umfassendem Support wird das System gehärtet und "
                           "ist leicht anpassbar. Dies ist besonders wichtig im Kontext von "
                           "Industrie 4.0, wo Systeme stark "
                           "miteinander vernetzt sind und eine gute Handhabbarkeit sowie Unterstützung erfordern. \n\n"
                           "(Quelle 6, 7, 8)", "Anwendung von Linux in der Industrie")

        topic7_node = Node("1. Nokia Foundation Award (1997)\n\n"
                           "2. Lifetime Achievement Award des Uniforums (1997)\n\n"
                           "3. Ehrendoktor der Universität Stockholm (1999): Die Universität Stockholm ernannte"
                           "Linus Torvalds 1999 zu ihrem bis dahin jüngsten Ehrendoktor.\n\n"
                           "4. Person des Jahres des PC Magazines (1999):\n\n"
                           "5. Reader’s Digest Europäer des Jahres 2000 (2000): Linus Torvalds wurde 2000 als"
                           "Europäer des Jahres vom Reader´s Digest ausgezeichnet.\n\n"
                           "6. Takeda-Preis (gemeinsam mit Richard Stallman und Ken Sakamura) (2001): Im Jahr"
                           "2001 erhielt Linus Torvalds den Takeda-Preis gemeinsam mit Richard Stallman und Ken"
                           "Sakamura.\n\n"
                           "7. Economist-Award (2004): Linus Torvalds erhielt den Economist-Award im Jahr 2004.\n\n"
                           "8. Millennium Technology Prize der Millennium Prize Foundation (2012): Im Jahr 2012"
                           "wurde Linus Torvalds mit dem Millennium Technology Prize der Millennium Prize"
                           "Foundation ausgezeichnet.\n\n"
                           "9. Computer Pioneer Award der IEEE Computer Society (2014): Linus Torvalds erhielt den"
                           "Computer Pioneer Award der IEEE Computer Society im Jahr 2014.\n\n"
                           "10.IEEE Masaru Ibuka Consumer Electronics Award (2018): Im Jahr 2018 wurde Linus"
                           "Torvalds mit dem IEEE Masaru Ibuka Consumer Electronics Award ausgezeichnet.\n\n"
                           "(Quelle 9,10)",
                           "Anerkennungen und Auszeichnungen")

        topic8_node = Node("Reisen und Vorträge"
                           "Wenn man nach Reisen und Vorträge über Linus sucht, findet man nicht viel. "
                           "Das liegt aber an "
                           "Linus selbst. Er spricht davon, dass er sich mit"
                           " Software beschäftigt, und nicht dafür da ist um in "
                           "der Öffentlichkeit zu sprechen. Ihm wäre es unklar, in was die "
                           "Menschen interessiert wären.\n\n "
                           "Folglich sind nur wenige Auftritte von Linus in der Öffentlichkeit bekannt.\n\n "
                           "Es sind aber vier größere Events bekannt, die Linus zumindest einmal "
                           "besucht hat. Das wäre zum "
                           "einem die LinuxCon und CloudOpen. Dieses Event fokussiert sich dabei auf die Open Source "
                           "Politik und Linux selber.\n\n "
                           "Des weiteren ist Linus in der Vergangenheit auch schon bei der Embedded "
                           "Linux Conference (ELC) "
                           "zu Gast gewesen. Dies fokussiert sich auf Linux in eingebetteten Systemen.\n\n "
                           "Der Linux Linux Kernel Summit wird von Linus regelmäßig besucht. Dieser bringt "
                           "die Entwickler "
                           "und Beteiligte des Linux-Kernel zusammen, um technische Diskussionen zu führen. \n\n"
                           "Des weiteren hat sich Linus auch bei Open Source Veranstaltungen sehen lassen. "
                           "Diese beschäftigen "
                           " sich hauptsächlich mit der Zukunft von Open Source. \n\n"
                           "(Quelle 11, 12, 13, 19)", "Reisen und Vorträge")

        topic9_node = Node("Eines der bekanntesten Projekte neben Linux selber ist die Versionsverwaltung Git. "
                           "(Siehe mehr im Knoten „Entwicklung von der Versionsverwaltung git“) \n\n"
                           "Dennoch war dies nicht Linus einziges Projekt neben Linux. Linus Torvalds zeigt eine "
                           "leidenschaftliche Neigung zum Tauchen. Im Herbst 2011, als die "
                           "Entwicklung des Linux-Kernels "
                           "kurzzeitig stagnierte, wurde die Software Subsurface ins Leben "
                           "gerufen. Zu dieser Zeit suchte "
                           "Torvalds nach einer geeigneten Anwendung zur Verwaltung von Taucher-Logbucheinträgen und "
                           "gründete zusammen mit anderen Entwicklern Subsurface. "
                           "Seit Herbst 2012 liegt die Leitung des "
                           "Projekts in den Händen von Dirk Hohndel. Subsurface ist in über einem Dutzend Sprachen "
                           "verfügbar und kompatibel mit Linux, Windows und Mac OS X.\n "
                           "Die Software ermöglicht nicht nur das automatische Protokollieren von Tauchgängen, sondern "
                           "erlaubt auch das manuelle Hinzufügen zahlreicher Details wie "
                           "Ausrüstung, verwendete Gase und "
                           "Tankgrößen. Es besteht außerdem die Option, Notizen zu "
                           "hinterlassen, den Tauchplatz zu bewerten "
                           "und GPS-Koordinaten zu speichern. Die Daten werden in einer "
                           "XML-Datei gespeichert, die flexibel "
                           "analysiert werden kann. Subsurface kann auch über das Web "
                           "genutzt werden, und Informationen "
                           "dazu sind unter api.hohndel.org verfügbar. \n\n "
                           "Zusätzlich bietet Subsurface einen Tauchplaner, mit dem umfangreiche Multilevel-Tauchgänge "
                           "geplant werden können. Unter Berücksichtigung des Luftverbrauchs (SAC) kann sichergestellt "
                           "werden, dass die Gasmenge in den Tanks für den Tauchgang ausreicht. "
                           "Es wird jedoch betont, dass "
                           "es sich um eine Simulation handelt und echte Tauchbedingungen wie "
                           "Wetter und Strömung nicht "
                           "berücksichtigt werden können. Der Tauchplaner sollte daher mit "
                           "Vorsicht verwendet werden. \n\n"
                           "(Quelle 15)",
                           "Weitere Projekte von Linus Torvald")

        topic10_node = Node("Die Linux Foundation (LF) ist ein gemeinnütziges Technologie-Konsortium mit über 1.000 "
                            "Mitgliedern, das sich der Finanzierung von Open-Source-Entwicklungen in der IT widmet. "
                            "Gegründet im Jahr 2007 durch den Zusammenschluss der "
                            "OSDL und der FSG, arbeitet die Stiftung "
                            "in enger Koordination mit Linus Torvalds, einem führenden Denker im Bereich Linux. Die LF "
                            "unterstützt und finanziert offene IT-Projekte im Linux-Universum "
                            "und gilt als der weltweit größte "
                            "Open-Source Fachverband. \n\n"
                            "Mit Sitz in San Francisco/CA beschäftigt die LF 150 Mitarbeiter und "
                            "finanziert Projekte durch "
                            "Mitgliederbeiträge, Sponsorengelder und Spenden. Sie agiert als neutraler"
                            " Eigentümer aller Linux "
                            "Kernel-Ressourcen, Domänen und Marken und bietet``Foundation as a Service´´ "
                            "für die Community "
                            "an, indem sie Rahmenbedingungen für Projekte schafft. \n\n"
                            "Linus Torvalds, trat der Vorgänger-Organisation OSDL im Jahr 2003 bei und "
                            "widmete seine "
                            "gesamte Arbeitszeit der Linux-Entwicklung. Er spielt eine wichtige Rolle in"
                            "der LF, da er die "
                            "Markennamen-Rechte für``Linux´´ besitzt, und die LF verpflichtet sich, seine"
                            " Forschungsaktivitäten "
                            "und die anderer Linux-Visionäre zu finanzieren.\n\n "
                            "Die mehr als 1.000 LF-Mitglieder stammen aus verschiedenen IT-Segmenten, darunter Google, "
                            "Microsoft und QuIC. Nicht-IT-Mitglieder wie Twitter und Toyota zeigen die"
                            " branchenübergreifende "
                            "Bedeutung. Die LF finanziert sich über Mitgliedsbeiträge in den Kategorien "
                            "Platinum, Gold und "
                            "Silver Members. \n\n"
                            "Die LF organisiert Arbeitsgruppen, darunter die Linux Standard Base für "
                            "Standardisierung, Linux "
                            "Open Printing für professionelle Drucker-Lösungen, Linux Cloud Native "
                            "Computing Foundation "
                            "für Cloud Computing, Linux openHPC für High-End Rechenstrukturen und Linux Accessibility "
                            "Standards für zugängliche Linux-Systeme. \n\n"
                            "Das LF-Stiftungskonzept passt sich den Anforderungen der "
                            "``Open Source´´ Philosophie an und "
                            "bietet einer wachsenden Entwickler-Community Hersteller neutralen Ressourcen. \n\n"
                            "(Quelle 16)",
                            "Linux Foundation")

        topic11_node = Node("Versionsverwaltung git "
                            "Git ist das weltweit am meisten genutzte moderne Versionskontrollsystem, "
                            "das im Jahr 2005 von "
                            "Linus Torvalds, entwickelt wurde. Es handelt sich um ein ausgereiftes und "
                            "aktiv gepflegtes Open- "
                            "Source-Projekt, das von zahlreichen Softwareprojekten, sowohl kommerziell "
                            "als auch im Open- "
                            "Source-Bereich, weit verbreitet ist. Git ist bei vielen "
                            "Softwareentwicklern, die auf der Suche nach "
                            "Positionen sind, sehr bekannt. Zudem lässt es sich nahtlos in "
                            "verschiedene Betriebssysteme und "
                            "integrierte Entwicklungsumgebungen (IDEs) integrieren. \n"
                            "Die verteilte Architektur von Git ist ein Beispiel für ein "
                            "verteiltes Versionskontrollsystem (DVCS), "
                            "das es ermöglicht, dass jede Arbeitskopie eines Entwicklers "
                            "gleichzeitig eine Repository ist, das den "
                            "vollständigen Verlauf aller Änderungen enthält. Im Gegensatz zu"
                            " älteren Versionssystemen wie "
                            "CVS oder Subversionen, bei denen der gesamte Versionsverlauf "
                            "an einem zentralen Ort liegt, bietet "
                            "Git eine dezentrale Struktur. \n"
                            "Git legt den Fokus auf Performance, Sicherheit und Flexibilität und"
                            " verwendet Algorithmen, die auf "
                            "umfassenden Kenntnissen häufiger Attribute echter "
                            "Quellcode-Dateibäume basieren. In Bezug auf "
                            "Leistung bietet Git optimale Performance für Aktivitäten wie Commits,"
                            " Branching, Merging und "
                            "den Vergleich älterer Versionen. \n"
                            "Es vermeidet die Irreführung durch Dateinamen und konzentriert sich "
                            "stattdessen auf den Inhalt der "
                            "Dateien, was besonders wichtig ist, da Quellcode-Dateien häufig "
                            "umbenannt, aufgeteilt und neu "
                            "angeordnet werden. Die verteilte Natur von Git ermöglicht eine "
                            "schnelle und zuverlässige Arbeit "
                            "auch ohne Netzwerkzugriff. Ein weiterer Schwerpunkt von Git "
                            "liegt auf der Sicherheit, da die "
                            "Integrität des Quellcodes durch den Einsatz des kryptografisch "
                            "sicheren Hashing-Algorithmus "
                            "SHA1 gewährleistet wird. \n"
                            "Dies schützt den Code und den Änderungsverlauf vor versehentlichen oder vorsätzlichen "
                            "Änderungen. Die Flexibilität von Git zeigt sich in seinem "
                            "Support für verschiedene nicht-lineare "
                            "Entwicklungs-Workflows, seiner Effizienz bei Projekten jeder "
                            "Größe und seiner Kompatibilität mit "
                            "verschiedenen Systemen und Protokollen. \n"
                            "Git unterstützt Branching und Tagging in bevorzugter Weise und "
                            "speichert Operationen, die sich auf "
                            "Branches und Tags auswirken, als Teil des Änderungsverlaufs. Git wird "
                            "von vielen Softwareteams "
                            "als beste Option betrachtet, da es über Funktionen, Performance, "
                            "Sicherheit und Flexibilität verfügt. "
                            "Git ist weit verbreitet und mit einem großen Talentpool versehen, "
                            "und wird als Open-Source- "
                            "Projekt von einer starken Community unterstützt. Dies führt zu einer "
                            "breiten Benutzerbasis und "
                            "umfassender Dokumentation. \n"
                            "Es gab in der Vergangenheit Kritikpunkte an Git, da es sehr Anfänger "
                            "unfreundlich ist. Dies verleitet "
                            "manche Teams dazu, an zentralen Repositorys festzuhalten. \n"
                            "Trotz dieser Punkte überwiegen die Vorteile von Git, und viele "
                            "Unternehmen verlassen sich auf "
                            "seine Qualität und Flexibilität für effektive Versionskontrolle und Zusammenarbeit in der "
                            "Softwareentwicklung.\n\n"
                            "(Quelle17)",
                            "Versionsverwaltung git")

        topic12_node = Node("Über soziales Engagement von Linus Torvald ist wenig bekannt. Jedoch "
                            "spiegelt die Tatsache das "
                            "alle Entwicklungen von Linus Open Source sind wieder, dass ihm bewusst ist. "
                            "Das andere davon "
                            "profitieren, seine Produkte zu verwenden. \n "
                            "So gesehen trägt Linus zum Allgemeinwohl bei mit seinen Open Source Initiativen. ",
                            "Soziales Engagement und Wohltätigkeitsarbeit")

        topic13_node = Node("Seine Vision war es, ein Betriebssystem zu entwickeln, das nicht nur "
                            "seinen eigenen Bedürfnissen "
                            "gerecht wurde, sondern auch für die Gemeinschaft zugänglich war. Torvalds "
                            "begann mit dem "
                            "Schreiben des Linux-Kernels, dem Herzstück des Betriebssystems, das die "
                            "Kommunikation mit der "
                            "Hardware ermöglichte. Von Anfang an teilte er seinen Code mit anderen, "
                            "und das Projekt wurde zu "
                            "einem wegweisenden Open-Source-Unterfangen. \n\n"
                            "Durch die Entscheidung, Linux unter der GNU General Public License (GPL) "
                            "zu veröffentlichen, "
                            "legte Torvalds den Grundstein für eine Ideologie von Freiheit und Zusammenarbeit in der "
                            "Softwareentwicklung. Diese Lizenz ermöglichte es jedem, den Quellcode zu verwenden, zu "
                            "modifizieren und die modifizierte Version ebenfalls unter derselben "
                            "Lizenz zu veröffentlichen. \n\n"
                            "Der frühe Erfolg von Linux basierte auf einer wachsenden Community von Entwicklern, die "
                            "begeistert von der Idee waren, an einem gemeinsamen Projekt zu arbeiten. "
                            "Diese Gemeinschaft "
                            "entwickelte nicht nur den Linux-Kernel weiter, sondern schuf "
                            "auch verschiedene Distributionen, die "
                            "den unterschiedlichen Anforderungen gerecht wurden. Torvalds' kühnes Unterfangen, ein "
                            "Betriebssystem zu schaffen, das auf Freiheit und Zusammenarbeit "
                            "basiert, markierte den Beginn "
                            "einer Revolution. Sein Beitrag zur Open-Source-Bewegung ist nicht"
                            " nur technisch, sondern auch "
                            "ideologisch wegweisend. Linux steht für die Überzeugung, "
                            "dass Software für alle frei zugänglich "
                            "sein sollte, und hat damit den Grundstein für eine neue Ära "
                            "in der Softwareentwicklung gelegt. \n\n"
                            "(Quelle 18)",
                            "Beitrag von Linux zur Open-Source Bewegung / Visionen von Linus Torvald")

        topic14_node = Node("In den jungen Jahren hatte Linus Torvald bei der Entwicklung von Linux ein "
                            "ernsthaftes Problem. Er hatte einen Mangel Ressourcen. Es mangelte "
                            "an guter Hardware und Geld für bessere Hardware. \n\n"
                            "Zudem war Linus nicht alleine an dem Projekt beteiligt. Viele Programmierer "
                            "haben Anteil an der Produktion gehabt. Das heißt, dass der Code fragmentiert war. "
                            "Dies gestaltete sich als schwierig wieder zu defragmentieren. \n\n"
                            "Linux musste und muss sich aktuell immer noch gegen Microsoft und Co. Behaupten. "
                            "Der größte Teil der PC User besteht nach wie vor aus Windows Usern. Dennoch bekommt "
                            "Linux in letzter Zeit Zuwachs von Gamer durch das Übersetzungstool Proton, welches es "
                            "ermöglicht grafische Anwendungen auf Linux auszuführen, die für Microsoft Windows "
                            "entwickelt wurden. \n\n"
                            "(Quelle 2 , 19, 20)",
                            "Herausforderungen und Meilensteine (Entwicklung von Linux)")

        topic15_node = Node("Linux hat einen erheblichen Einfluss auf die Technologiebranche ausgeübt "
                            "und ist zu einem nicht weg zu denkenden Bestandteil in verschiedenen Bereichen "
                            "geworden. Als Betriebssystem, das frei verfügbar und quelloffen ist, hat Linux "
                            "eine breite Akzeptanz gefunden und dient als Grundlage für zahlreiche "
                            "Softwareentwicklungen. Es bildet das Fundament für Server-Infrastrukturen "
                            "weltweit, was zu einer stabilen und sicheren Basis für Websites, Anwendungen "
                            "und Dienstleistungen führt. \n\n"
                            "Die Verwendung von Linux in Embedded-Systemen und IoT-Geräten hat ebenfalls "
                            "zugenommen, was zur Vernetzung verschiedener Geräte beiträgt. Die Android-Plattform, "
                            "die auf dem Linux-Kernel basiert, beherrscht den Mobilgerätemarkt.  \n\n"
                            "Entwickler schätzen die Flexibilität und Anpassungsfähigkeit von Linux, die es "
                            "ermöglichen, maßgeschneiderte Lösungen zu erstellen. Die offene Natur von Linux "
                            "fördert die Zusammenarbeit und den Wissensaustausch in der Entwicklergemeinschaft. "
                            "Darüber hinaus hat Linux dazu beigetragen, die Kosten in der Unternehmenswelt zu senken, "
                            "da es eine kostengünstige Alternative zu proprietären Betriebssystemen darstellt. \n\n "
                            "Insgesamt hat Linux die technologische Landschaft durch seine Offenheit, Stabilität "
                            "und Vielseitigkeit nachhaltig geprägt. \n\n"
                            "(Quelle21)",
                            "Gesamter langfristiger Einfluss von Linux auf die Technologiebranche")

        sources_node = Node("1.Quelle:\n "
                            "https://www.zdnet.com/article/linus-torvalds-rust-will-go-into-linux-6-1/ \n"
                            "Zugriffszeit: 09:00 Uhr 27.11.2023\n\n "
                            "2.Quelle \n"
                            "https://de.wikipedia.org/wiki/Linus_Torvalds \n"
                            "-abschnitt Kindheit und Jugend\n"
                            "Zugriffszeit: 09:44 Uhr 27.11.2023 \n\n"
                            "3.Quelle \n"
                            "https://www.operating-system.org/betriebssystem/_german/bs-linux.htm \n"
                            "Zugriffszeit: 11:36 Uhr 27.11.2023 \n\n"
                            "4.Quelle \n"
                            "https://www.golem.de/news/linus-torvalds-open-source-ist-was-fuer-egoisten-1206-92498"
                            ".html \n"
                            "Zugriffszeit: 12:06 Uhr 27.11.2023\n\n "
                            "5.Quelle \n"
                            "https://www.gnu.org/philosophy/linux-gnu-freedom.de.html \n"
                            "Zugriffszeit: 13:20 Uhr 27.11.2023 \n\n"
                            "6.Quelle \n"
                            "https://www.computerweekly.com/de/ratgeber/Die-5-wichtigsten-Linux-Distributionen-"
                            "fuer-Unternehmen \n"
                            "Zugriffszeit:  13:45 Uhr 27.11.2023 \n\n"
                            "7.Quelle \n"
                            "https://www.computer-automation.de/steuerungsebene/industrie-pc/windows-und-echtzeit-"
                            "linux-vereint.168695.html \n"
                            "Zugriffszeit: 13:50 Uhr 27.11.2023 \n\n"
                            "8.Quelle \n"
                            "https://www.all-electronics.de/elektronik-entwicklung/leichtere-entwicklung-"
                            "sicherer-embedded-linux-anwendungen-757.html \n"
                            "Zugriffszeit: 14:00 Uhr 27.11.2023 \n\n"
                            "9.Quelle \n"
                            "https://dewiki.de/Lexikon/Linus_Torvalds#Das_Leben_abseits_von_Linux \n"
                            "Zugriffszeit: 15:15 Uhr 27.11.2023\n\n "
                            "10.Quelle \n"
                            "https://www.einstieg-informatik.de/linus-torvalds/ \n"
                            "Zugriffszeit: 15:17 Uhr 27.11.2023 \n\n"
                            "11.Quelle \n"
                            "https://www.linux-magazin.de/ausgaben/2012/01/linuxcon/ \n"
                            "Zugriffszeit: 10:55 Uhr 28.11.2023 \n\n"
                            "12.Quelle \n"
                            "https://www.linuxfoundation.jp/blog/2017/01/linus-torvalds-guy-hoffman-and-imad-"
                            "sousou-to-speak-at-embedded-linux-conference-next-month/\n"
                            "Zugriffszeit: 11:02 Uhr 28.11.2023\n\n"
                            "13.Quelle\n"
                            "https://www.linux-magazin.de/ausgaben/2007/11/an-der-quelle/ \n"
                            "Zugriffszeit: 11:10 Uhr 28.11.2023 \n\n"
                            "14.Quelle \n"
                            "https://www.zdnet.com/article/linus-torvalds-open-source-summit-fireside-chat/ \n"
                            "Zugriffszeit: 11:17 Uhr 28.11.2023 \n\n"
                            "15.Quelle \n"
                            "https://www.bitblokes.de/open-source-tauchlog-software-subsurface-von-linus-"
                            "torvalds-mitentwickelt/ \n"
                            "Zugriffszeit: 12:30 Uhr 28.11.2023 \n\n"
                            "16.Quelle \n"
                            "https://www.dev-insider.de/was-ist-die-linux-foundation-a-45d64205ac3a42ec80"
                            "d32ee43b2db2d0/\n"
                            "Zugriffszeit: 12:47 Uhr 28.11.2023 \n\n"
                            "17.Quelle \n"
                            "https://www.atlassian.com/de/git/tutorials/what-is-git\n"
                            "Zugriffszeit: 14:02 Uhr 28.11.2023 \n\n"
                            "18.Quelle \n"
                            "https://addis-techblog.de/2023/11/die-faszinierende-geschichte-von-linux-vom-"
                            "hobbyprojekt-zum-open-source-giganten/ \n"
                            "Zugriffszeit: 14:25 Uhr 28.11.2023 \n\n"
                            "19.Quelle \n"
                            "https://de.wikipedia.org/wiki/Proton_(Software)\n"
                            "Zugriffszeit: 14:40 Uhr 28.11.2023 \n\n"
                            "20.Quelle \n"
                            "https://de.statista.com/statistik/daten/studie/157902/umfrage/marktanteil-der-"
                            "genutzten-betriebssysteme-weltweit-seit-2009/ \n"
                            "Zugriffszeit: 14:45 Uhr 28.11.2023 \n\n"
                            "21.Quelle \n"
                            "https://www.computerweekly.com/de/definition/Android-OS \n"
                            "Zugriffszeit: 15:00 Uhr 28.11.2023\n\n",
                            "Quellenverzeichniss")

        """
        Hinzufügen zum Graphen
        """

        graph.add_new_node_to_graph(header_linus_node)
        graph.add_new_node_to_graph(topic_node)
        graph.add_new_node_to_graph(topic1_node)
        graph.add_new_node_to_graph(topic2_node)
        graph.add_new_node_to_graph(topic3_node)
        graph.add_new_node_to_graph(topic3v1_node)
        graph.add_new_node_to_graph(topic3v2_node)
        graph.add_new_node_to_graph(topic3v3_node)
        graph.add_new_node_to_graph(topic4_node)
        graph.add_new_node_to_graph(topic5_node)
        graph.add_new_node_to_graph(topic5v1_node)
        graph.add_new_node_to_graph(topic5v2_node)
        graph.add_new_node_to_graph(topic5v3_node)
        graph.add_new_node_to_graph(topic6_node)
        graph.add_new_node_to_graph(topic7_node)
        graph.add_new_node_to_graph(topic8_node)
        graph.add_new_node_to_graph(topic9_node)
        graph.add_new_node_to_graph(topic10_node)
        graph.add_new_node_to_graph(topic11_node)
        graph.add_new_node_to_graph(topic12_node)
        graph.add_new_node_to_graph(topic13_node)
        graph.add_new_node_to_graph(topic14_node)
        graph.add_new_node_to_graph(topic15_node)
        graph.add_new_node_to_graph(sources_node)

        """
        Verbindungen der Knoten
        """
        header_linus_node.connect(topic_node)
        header_linus_node.connect(topic1_node)
        header_linus_node.connect(topic2_node)
        header_linus_node.connect(topic3_node)
        topic3_node.connect(topic3v1_node)
        topic3_node.connect(topic3v2_node)
        topic3_node.connect(topic3v3_node)
        header_linus_node.connect(topic4_node)
        header_linus_node.connect(topic5_node)
        topic5_node.connect(topic5v1_node)
        topic5_node.connect(topic5v2_node)
        topic5_node.connect(topic5v3_node)
        header_linus_node.connect(topic6_node)
        header_linus_node.connect(topic7_node)
        header_linus_node.connect(topic8_node)
        header_linus_node.connect(topic9_node)
        topic9_node.connect(topic11_node)
        header_linus_node.connect(topic10_node)
        header_linus_node.connect(topic12_node)
        header_linus_node.connect(topic13_node)
        header_linus_node.connect(topic14_node)
        header_linus_node.connect(topic15_node)
        header_linus_node.connect(sources_node)
